const alunoFields = [
  // {
  //   name: "codigo",
  //   label: "ID",
  //   type: "number",
  //   className: "inputNumber",
  //   readOnly: true,
  //   divisorClass: "divisor1",
  // },
  {
    name: "nome",
    label: "Nome",
    type: "text",
    className: "inputText",
    placeholder: "Nome do aluno",
    required: true,
    divisorClass: "divisor2",
  },
  {
    name: "dataNascimento",
    label: "Data de nascimento",
    type: "date",
    className: "inputData",
    required: true,
    divisorClass: "divisor3",
  },
  {
    name: "nomeMae",
    label: "Nome da mãe",
    type: "text",
    className: "inputText",
    placeholder: "Nome da mãe do aluno",
    required: true,
    divisorClass: "divisor2",
  },
  {
    name: "cidade",
    label: "Cidade",
    type: "text",
    className: "inputText",
    placeholder: "Nome da cidade",
    required: true,
    divisorClass: "divisor3",
  },
  {
    name: "turma",
    label: "Turma",
    type: "select",
    options: ["1W", "1X", "1Y", "2W", "2X", "2Y", "3W", "3X", "3Y"],
    className: "inputSelect",
    required: true,
    divisorClass: "divisor1",
  },
  {
    name: "escola",
    label: "Escola",
    type: "text",
    className: "inputText",
    placeholder: "Nome da escola",
    required: true,
    divisorClass: "divisor4",
  },
  {
    name: "ra",
    label: "RA",
    type: "number",
    className: "inputNumber",
    placeholder: "Número do RA",
    required: true,
    divisorClass: "divisor3",
  },
  {
    name: "matricula",
    label: "Matricula",
    type: "number",
    className: "inputNumber",
    placeholder: "Número da matrícula",
    required: true,
    divisorClass: "divisor3",
  },
  {
    name: "sexo",
    label: "Sexo",
    type: "select",
    options: ["feminino", "masculino"],
    className: "inputSelect",
    required: true,
    divisorClass: "divisor1",
  },
  {
    name: "email",
    label: "E-mail do usuário",
    type: "text",
    className: "inputText",
    placeholder: "E-mail do usuário",
    required: true,
    divisorClass: "divisor2",
  },
  {
    name: "senha",
    label: "Senha",
    type: "password",
    className: "inputSenha",
    placeholder: "Senha",
    required: true,
    divisorClass: "divisor3",
  },
];

export default alunoFields;
