const materialFields = [
  // {
  //   name: "codigoMaterial",
  //   label: "Código do Material",
  //   type: "number",
  //   className: "inputNumber",
  //   readOnly: true,
  //   divisorClass: "divisor1",
  // },
  {
    name: "nomeMaterial",
    label: "Nome do Material",
    type: "text",
    className: "inputText",
    placeholder: "Nome do material",
    required: true,
    divisorClass: "divisor2",
  },
  {
    name: "categoriaMaterial",
    label: "Categoria",
    type: "select",
    options: ["Livro", "Caderno", "Caneta", "Lápis", "Borracha", "Outro"],
    className: "inputSelect",
    required: true,
    divisorClass: "divisor3",
  },
  {
    name: "quantidade",
    label: "Quantidade",
    type: "number",
    className: "inputNumber",
    placeholder: "Quantidade disponível",
    required: true,
    divisorClass: "divisor2",
  },
  {
    name: "dataAquisicao",
    label: "Data de Aquisição",
    type: "date",
    className: "inputData",
    required: true,
    divisorClass: "divisor3",
  },
  {
    name: "fornecedor",
    label: "Fornecedor",
    type: "text",
    className: "inputText",
    placeholder: "Nome do fornecedor",
    required: true,
    divisorClass: "divisor4",
  },
  {
    name: "condicao",
    label: "Condição",
    type: "select",
    options: ["Novo", "Usado", "Danificado"],
    className: "inputSelect",
    required: true,
    divisorClass: "divisor1",
  },
  {
    name: "localArmazenamento",
    label: "Local de Armazenamento",
    type: "text",
    className: "inputText",
    placeholder: "Local onde o material está armazenado",
    required: true,
    divisorClass: "divisor2",
  },
  {
    name: "descricaoMaterial",
    label: "Descrição",
    type: "textarea",
    className: "inputTextArea",
    placeholder: "Descrição detalhada do material",
    required: false,
    divisorClass: "divisor3",
  },
    {
    name: "link",
    label: "Link do Material",
    type: "text",
    className: "inputText",
    placeholder: "Link do Material",
    // required: true,
    divisorClass: "divisor2",
  },

];

export default materialFields;
