const notasFaltasFields = [
  {
    name: "codigo",
    label: "ID",
    type: "number",
    className: "inputNumber",
    readOnly: true,
    divisorClass: "divisor1",
  },
  {
    name: "turma",
    label: "Turma",
    type: "select",
    options: ["1W", "1X", "1Y", "2W", "2X", "2Y", "3W", "3X", "3Y"],
    className: "inputSelect",
    divisorClass: "divisor2",
  },
  {
    name: "aluno",
    label: "Aluno",
    type: "select",
    options: [],
    className: "inputSelect",
    divisorClass: "divisor3",
  },
  {
    name: "bimestre",
    label: "Bimestre",
    type: "select",
    options: ["1", "2", "3", "4"],
    className: "inputSelect",
    divisorClass: "divisor1",
  },
  {
    name: "matematica",
    label: "Matemática",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasMatematica",
    label: "Faltas Matemática",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "portugues",
    label: "Português",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasPortugues",
    label: "Faltas Português",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "historia",
    label: "História",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasHistoria",
    label: "Faltas História",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "quimica",
    label: "Química",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasQuimica",
    label: "Faltas Química",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "geografia",
    label: "Geografia",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasGeografia",
    label: "Faltas Geografia",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "biologia",
    label: "Biologia",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasBiologia",
    label: "Faltas Biologia",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "sociologia",
    label: "Sociologia",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasSociologia",
    label: "Faltas Sociologia",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "filosofia",
    label: "Filosofia",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasFilosofia",
    label: "Faltas Filosofia",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "ingles",
    label: "Inglês",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasIngles",
    label: "Faltas Inglês",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "edFisica",
    label: "Educação Física",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasEdFisica",
    label: "Faltas Educação Física",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
  {
    name: "fisica",
    label: "Física",
    type: "number",
    className: "inputNumber",
    placeholder: "N",
    min: "0",
    max: "10",
    divisorClass: "divisor4",
  },
  {
    name: "faltasFisica",
    label: "Faltas Física",
    type: "number",
    className: "inputNumber",
    placeholder: "F",
    min: "0",
    divisorClass: "divisor5",
  },
];

export default notasFaltasFields;
